import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import KarnaliUpdatesNavbar from "@/components/layout/navbar";
import KarnaliUpdatesFooter from "@/components/layout/footer";
import { Providers } from "@/components/layout/theme";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", geist.variable)}
    >
      <body className="flex min-h-full flex-col">
        <Providers>
          <KarnaliUpdatesNavbar />
          <div className="flex min-h-0 flex-1 flex-col">{children}</div>
          <KarnaliUpdatesFooter />
        </Providers>
      </body>
    </html>
  );
}
